//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOO_CLIENT.OrderService2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="uk.ac.bcu.soa.wcf")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CartIdField, value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDateTime {
            get {
                return this.OrderDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDateTimeField, value) != true)) {
                    this.OrderDateTimeField = value;
                    this.RaisePropertyChanged("OrderDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Feedback", Namespace="uk.ac.bcu.soa.wcf")]
    [System.SerializableAttribute()]
    public partial class Feedback : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerFeedbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeedbackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFeedback {
            get {
                return this.CustomerFeedbackField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerFeedbackField, value) != true)) {
                    this.CustomerFeedbackField = value;
                    this.RaisePropertyChanged("CustomerFeedback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeedbackId {
            get {
                return this.FeedbackIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FeedbackIdField, value) != true)) {
                    this.FeedbackIdField = value;
                    this.RaisePropertyChanged("FeedbackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartItem", Namespace="uk.ac.bcu.soa.wcf")]
    [System.SerializableAttribute()]
    public partial class CartItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductQuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartId {
            get {
                return this.CartIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CartIdField, value) != true)) {
                    this.CartIdField = value;
                    this.RaisePropertyChanged("CartId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductQuantity {
            get {
                return this.ProductQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductQuantityField, value) != true)) {
                    this.ProductQuantityField = value;
                    this.RaisePropertyChanged("ProductQuantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="uk.ac.bcu.soa.wcf", ConfigurationName="OrderService2.IOrderRegistry")]
    public interface IOrderRegistry {
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/AddToCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/AddToCartResponse")]
        bool AddToCart(string product_id, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/AddToCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/AddToCartResponse")]
        System.Threading.Tasks.Task<bool> AddToCartAsync(string product_id, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/RemoveFromCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/RemoveFromCartResponse")]
        bool RemoveFromCart(string product_id, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/RemoveFromCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/RemoveFromCartResponse")]
        System.Threading.Tasks.Task<bool> RemoveFromCartAsync(string product_id, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/ProcessOrder", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/ProcessOrderResponse")]
        int ProcessOrder(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/ProcessOrder", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/ProcessOrderResponse")]
        System.Threading.Tasks.Task<int> ProcessOrderAsync(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetOrder", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetOrderResponse")]
        SOO_CLIENT.OrderService2.Order GetOrder(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetOrder", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetOrderResponse")]
        System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Order> GetOrderAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllOrders", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllOrdersResponse")]
        SOO_CLIENT.OrderService2.Order[] GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllOrders", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllOrdersResponse")]
        System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Order[]> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GiveFeedback", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GiveFeedbackResponse")]
        bool GiveFeedback(string orderId, string feedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GiveFeedback", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GiveFeedbackResponse")]
        System.Threading.Tasks.Task<bool> GiveFeedbackAsync(string orderId, string feedback);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllFeedbacks", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllFeedbacksResponse")]
        SOO_CLIENT.OrderService2.Feedback[] GetAllFeedbacks();
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllFeedbacks", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetAllFeedbacksResponse")]
        System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Feedback[]> GetAllFeedbacksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCartDetails", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCartDetailsResponse")]
        SOO_CLIENT.OrderService2.CartItem[] GetCartDetails(string cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCartDetails", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCartDetailsResponse")]
        System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.CartItem[]> GetCartDetailsAsync(string cartId);
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCurrentCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCurrentCartResponse")]
        System.Collections.Generic.Dictionary<string, int> GetCurrentCart();
        
        [System.ServiceModel.OperationContractAttribute(Action="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCurrentCart", ReplyAction="uk.ac.bcu.soa.wcf/IOrderRegistry/GetCurrentCartResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCurrentCartAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderRegistryChannel : SOO_CLIENT.OrderService2.IOrderRegistry, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderRegistryClient : System.ServiceModel.ClientBase<SOO_CLIENT.OrderService2.IOrderRegistry>, SOO_CLIENT.OrderService2.IOrderRegistry {
        
        public OrderRegistryClient() {
        }
        
        public OrderRegistryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderRegistryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderRegistryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderRegistryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddToCart(string product_id, int quantity) {
            return base.Channel.AddToCart(product_id, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> AddToCartAsync(string product_id, int quantity) {
            return base.Channel.AddToCartAsync(product_id, quantity);
        }
        
        public bool RemoveFromCart(string product_id, int quantity) {
            return base.Channel.RemoveFromCart(product_id, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveFromCartAsync(string product_id, int quantity) {
            return base.Channel.RemoveFromCartAsync(product_id, quantity);
        }
        
        public int ProcessOrder(string customerId) {
            return base.Channel.ProcessOrder(customerId);
        }
        
        public System.Threading.Tasks.Task<int> ProcessOrderAsync(string customerId) {
            return base.Channel.ProcessOrderAsync(customerId);
        }
        
        public SOO_CLIENT.OrderService2.Order GetOrder(string orderId) {
            return base.Channel.GetOrder(orderId);
        }
        
        public System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Order> GetOrderAsync(string orderId) {
            return base.Channel.GetOrderAsync(orderId);
        }
        
        public SOO_CLIENT.OrderService2.Order[] GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Order[]> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public bool GiveFeedback(string orderId, string feedback) {
            return base.Channel.GiveFeedback(orderId, feedback);
        }
        
        public System.Threading.Tasks.Task<bool> GiveFeedbackAsync(string orderId, string feedback) {
            return base.Channel.GiveFeedbackAsync(orderId, feedback);
        }
        
        public SOO_CLIENT.OrderService2.Feedback[] GetAllFeedbacks() {
            return base.Channel.GetAllFeedbacks();
        }
        
        public System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.Feedback[]> GetAllFeedbacksAsync() {
            return base.Channel.GetAllFeedbacksAsync();
        }
        
        public SOO_CLIENT.OrderService2.CartItem[] GetCartDetails(string cartId) {
            return base.Channel.GetCartDetails(cartId);
        }
        
        public System.Threading.Tasks.Task<SOO_CLIENT.OrderService2.CartItem[]> GetCartDetailsAsync(string cartId) {
            return base.Channel.GetCartDetailsAsync(cartId);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetCurrentCart() {
            return base.Channel.GetCurrentCart();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCurrentCartAsync() {
            return base.Channel.GetCurrentCartAsync();
        }
    }
}
